Vic.SportStore/Vic.SportStore.WebApp/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Vic.SportStore.Domain.Entities;

namespace Vic.SportsStore.WebApp.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

Vic.SportStore/Vic.SportStore.WebApp/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vic.SportsStore.WebApp.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems/ItemsPerPage);  }
        }

    }
}

Vic.SportStore/Vic.SportStore.WebApp/Models/ProductsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Vic.SportsStore.Domain.Entities;

namespace Vic.SportsStore.WebApp.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }

        public string CurrentCategory { get; set; }
    }
}

Vic.SportStore/Vic.SportStore.WebApp/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vic.SportsStore.Domain.Abstract;
using Vic.SportsStore.Domain.Entities;
using Vic.SportsStore.WebApp.Models;
using Vic.SportStore.Domain.Entities;

namespace Vic.SportsStore.WebApp.Controllers
{
    public class CartController : Controller
    {
        private IProductsRepository repository;
        public CartController(IProductsRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository
            .Products
            .FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToRouteResult RemoveFromCart(Cart cart,int productId, string returnUrl)
        {
            Product product = repository
            .Products
            .FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        //private Cart GetCart()
        //{
        //    Cart cart = (Cart)Session["Cart"];
        //    if (cart == null)
        //    {
        //        cart = new Cart();
        //        Session["Cart"] = cart;
        //    }
        //    return cart;
        //}

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
    }
}

Vic.SportStore/Vic.SportStore.WebApp/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vic.SportsStore.Domain.Abstract;

namespace Vic.SportsStore.WebApp.Controllers
{
    public class NavController : Controller
    {
        public IProductsRepository repository { get; set; }
        public NavController(IProductsRepository repo)
        {
            repository = repo;
        }
        //public PartialViewResult Menu()
        //{
        //    IEnumerable<string> categories = repository
        //    .Products
        //    .Select(x => x.Category)
        //    .Distinct()
        //    .OrderBy(x => x);
        //    return PartialView(categories);
        //}

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository
            .Products
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

Vic.SportStore/Vic.SportStore.WebApp/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vic.SportsStore.Domain.Abstract;
using Vic.SportsStore.Domain.Concrete;
using Vic.SportsStore.Domain.Entities;
using Vic.SportsStore.WebApp.Models;
namespace Vic.SportsStore.WebApp.Controllers
{
    public class ProductsController : Controller
    {

        public const int PageSize = 3;
        //private IProductsRepository repository = new InMemoryProductRepository();

        //Property Dependecy 
        public IProductsRepository Repository { get; set; }

        //Constructor Dependecy
        //private IProductsRepository _repository;
        //public ProductsController(IProductsRepository Repository) 
        //{
        //    _repository = Repository;
        //}


        // GET: Products
        //public ActionResult Index()
        //{
        //    return View();
        //}
        public ViewResult List(string category,int page = 1)
        {
            //return View(Repository.Products);
            var result = Repository
                .Products
                .Where(p => category==null||p.Category== category)
                .OrderBy(p => p.ProductId)
                .Skip((page - 1) * PageSize)
                .Take(PageSize);

            var pageinfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = PageSize,
                TotalItems = Repository
                .Products
                .Where(p => category == null || p.Category == category)
                .Count()
            };

            var vm = new ProductsListViewModel
            { 
                PagingInfo = pageinfo,
                Products = result,
                CurrentCategory = category 
            };


            return View(vm);

        }

    }


}

Vic.SportStore/Vic.SportStore.WebApp/Views/Cart/Index.cshtml
@model Vic.SportsStore.WebApp.Models.CartIndexViewModel
@{
    ViewBag.Title = "Sports Store: Your Cart";
}
<style>
    #cartTable td {
        vertical-align: middle;
    }
</style>
<h2>Your cart</h2>
<table id="cartTable" class="table">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Product.Name</td>
                <td class="text-right">@line.Product.Price.ToString("c")</td>
                <td class="text-right">
                    @((line.Quantity * line.Product.Price).ToString("c"))
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("ProductId", line.Product.ProductId) 
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="btn btn-sm btn-warning" type="submit" value="Remove" />
                    }
                </td>
            </tr>
       }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue shopping</a>
</div>

Vic.SportStore/Vic.SportStore.WebApp/Views/Cart/Summary.cshtml
@model Vic.SportsStore.Domain.Entities.Cart 

<div class="navbar-right">
    @Html.ActionLink("Checkout", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class = "btn btn-default navbar-btn" })
</div>
<div class="navbar-text navbar-right">
    <b>Your cart:</b>
    @Model.Lines.Sum(x => x.Quantity) item(s),
    @Model.ComputeTotalValue().ToString("c")
</div>

Vic.SportStore/Vic.SportStore.WebApp/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Products", null, new { @class = "btn btn-block btn-default btn-lg" })

@*@Model.ToList().Count()*@ 

@foreach (var LinkCategoryName in Model)
{
    @Html.RouteLink(
    LinkCategoryName,
    new
    {
        controller = "Products",
        action = "List",
        category = LinkCategoryName,
        page = 1
    },
    new
    {
        @class = "btn btn-block btn-default btn-lg" + (LinkCategoryName == ViewBag.SelectedCategory ? " btn-primary" : "")
    }
    )
}

Vic.SportStore/Vic.SportStore.WebApp/Views/Products/List.cshtml
@model Vic.SportsStore.WebApp.Models.ProductsListViewModel
@{
    ViewBag.Title = "Products";
}@foreach (var p in Model.Products)
{
    @Html.Partial("ProductSummary", p)
}
<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x , category = Model.CurrentCategory}))
</div>

Vic.SportStore/Vic.SportStore.WebApp/Views/Shared/ProductSummary.cshtml
@model Vic.SportsStore.Domain.Entities.Product
<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProductId) 
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart" />
        </div>
    }
    <span class="lead"> @Model.Description</span>
</div>

Vic.SportStore/Vic.SportStore.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">SPORTS STORE</a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>